name: CI/CD for OMSDemo
on:
    push:
        branches: 
            - dev

jobs:
        build:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout code
                  uses: actions/checkout@v4.2.2
                - name: Set Short SHA Output
                  id: vars
                  run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
                - name: login to Dockerhub
                  uses: docker/login-action@v3
                  with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                - name: Setup Docker Buildx
                  uses: docker/setup-buildx-action@v3
                - name: Extract Docker Metadata
                  id: meta
                  uses: docker/metadata-action@v5.6.0
                  with:
                    images: akshay0918/omsdemo
                    tags: |
                      type=raw,value=latest,enable=${{ github.ref == 'refs/heads/dev' }}
                      type=sha,format=short
                - name: Build and Push Docker image
                  uses: docker/build-push-action@v6
                  with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: |
                      akshay0918/omsdemo:latest
                      akshay0918/omsdemo:${{ github.sha }}

                    labels: ${{ steps.meta.outputs.labels }}
                    no-cache: true  
        
        deploy:
            needs: build
            runs-on: self-hosted
            steps:
                - name: Checkout repository code
                  uses: actions/checkout@v4.2.2

                - name: Create .env
                  run: |
                    cat > .env <<EOF
                    APP_NAME=OMSDemo
                    APP_ENV=development
                    DEBUG=False

                    DATABASE_HOST=postgres
                    DATABASE_PORT=5432
                    DATABASE_NAME=omsdemo
                    DATABASE_USER=akshay
                    DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}

                    REDIS_HOST=redis
                    REDIS_PORT=6379

                    SECRET_KEY=${{ secrets.SECRET_KEY }}
                    ALGORITHM=HS256

                    ACCESS_TOKEN_EXPIRE_MINUTES=15
                    REFRESH_TOKEN_EXPIRE_DAYS=30
                    EOF
                - name: Pull and Start Docker Compose Locally
                  run: |
                    docker compose pull
                    docker compose up -d --remove-orphans
